example: # namespace
  counter: # node name
    ros__parameters:
      comment: "Launch"
  observer: # node name
    ros__parameters:
      comment: "Yes comments"
      blind: false
      offset: 10
      favorite:
        numbers_integers: [1, 2, 3, 4]
        numbers_doubles : [3.14, 2.718]
